version: "3.8"

services:
  
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: e-shop
  
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://user:pass@mongodb:27017/

    depends_on:
      - mongodb

  nodejs:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - "3100:3100"
    depends_on:
      - mongodb
      - redis

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

