apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: user
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: pass
        - name: ME_CONFIG_MONGODB_URL
          value: mongodb://user:pass@mongodb:27017/
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
spec:
  type: NodePort
  ports:
  - port: 8081
    nodePort: 30001
  selector:
    app: mongo-express

